### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'realizedPnL'  immediately after  " python main.py" is executed

### ISSUE THREAD

**Issue by developeralgo8888** [jamesmawm/High-Frequency-Trading-Model-with-IB#24]
Traceback (most recent call last):
  File "/home/miniconda3/lib/python3.8/site-packages/eventkit/event.py", line 184, in emit
    func(obj, *args)
  File "/developer/Downloads/High-Frequency-Trading-Model-with-IB/models/hft_model_1.py", line 78, in on_tick
    self.perform_trade_logic()
  File "/developer/Downloads/High-Frequency-Trading-Model-with-IB/models/hft_model_1.py", line 101, in perform_trade_logic
    self.print_strategy_params()
  File "/developer/Downloads/High-Frequency-Trading-Model-with-IB/models/hft_model_1.py", line 127, in print_strategy_params   
 rpnl=self.pnl.realizedPnL,
AttributeError: 'NoneType' object has no attribute 'realizedPnL'

Note sure what is missing in ib_sync or interactive Brokers response.

**Comment by pengfengyong** [comment]
I also meet this problem, whether you solved this problem?
